/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/UI/Button/Button.vue')['default']
    component: typeof import('vue')['component']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSprite: typeof import('./src/components/UI/IconSprite/IconSprite.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Modal: typeof import('./src/components/UI/Modal/Modal.vue')['default']
    StartScreen: typeof import('./src/components/StartScreen.vue')['default']
    TreeView: typeof import('./src/components/TreeView.vue')['default']
  }
}
